version: "3.5"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:0
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    #restart: always