version: "3.5"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:hyungdki
    ports:
      - "443:443"
    env_file:
      - .env
    depends_on:
      - wordpress
    networks:
      - inception_network
    volumes:
      - wordpress_volume:/var/www/html
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:hyundki
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception_network
    volumes:
      - wordpress_volume:/var/www/html
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:hyundki
    env_file:
      - .env
    networks:
      - inception_network
    volumes:
      - mariadb_volume:/var/lib/mysql
    restart: always

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    image: redis:hyungdki
    env_file:
      - .env
    depends_on:
      - wordpress
    networks:
      - inception_network
    volumes:
      - wordpress_volume:/var/www/html
    restart: always

  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    image: ftp:hyungdki
    ports:
      - "20:20"
      - "21:21"
      - "60000-60005:60000-60005"
    env_file:
      - .env
    depends_on:
      - wordpress
    networks:
      - inception_network
    volumes:
      - wordpress_volume:/var/www/html
    restart: always

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    image: adminer:hyungdki
    depends_on:
      - mariadb
    networks:
      - inception_network
    volumes:
      - wordpress_volume:/var/www/html
    restart: always
  
  website:
    container_name: website
    build: ./requirements/bonus/website
    image: website:hyungdki
    networks:
      - inception_network
    volumes:
      - wordpress_volume:/var/www/html
    restart: always

  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor
    image: cadvisor:hyungdki
    ports:
      - "8080:8080"
    networks:
      - inception_network
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/dis/:/dev/disk:ro
      - /var/run:/var/run:ro
    restart: always

networks:
  inception_network:
    name: inception_network
    driver: bridge


volumes:
  wordpress_volume:
    name: wordpress_volume
    driver: local
    driver_opts:
      device: /Users/kael/data/wordpress
      o: bind
      type: volumes

  mariadb_volume:
    name: mariadb_volume
    driver: local
    driver_opts:
      device: /Users/kael/data/mariadb
      o: bind
      type: volumes
