version: "3.5"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:hyungdki
    ports:
      - "443:443"
    env_file:
      - .env
    depends_on:
      - wordpress
    networks:
      - inception_network
    volumes:
      - wordpress_volume:/var/www/html
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:hyundki
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception_network
    volumes:
      - wordpress_volume:/var/www/html
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:hyundki
    env_file:
      - .env
    networks:
      - inception_network
    volumes:
      - mariadb_volume:/var/lib/mysql
    restart: always


networks:
  inception_network:
    name: inception_network
    driver: bridge


volumes:
  wordpress_volume:
    name: wordpress_volume
    driver: local

  mariadb_volume:
    name: mariadb_volume
    driver: local
