# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hyungdki <hyungdki@student.42seoul.kr>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/02/27 10:17:21 by hyungdki          #+#    #+#              #
#    Updated: 2024/02/27 20:45:27 by hyungdki         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM debian:bullseye

RUN apt update -y \
	&& apt install -y dumb-init \
                    vim \
                    procps \
                    dnsutils \
                    iputils-ping \
                    net-tools \
					php \
					php-bcmath \
					php-curl \
					php-imagick \
					php-intl \
					php-json \
					php-mbstring \
					php-mysql \
					php-xml \
					php-zip \
					php-fpm \
					php-cli

